config/routes.rb
Blackjack::Application.routes.draw do
  resources :games, except: [:index, :new, :create, :show, :edit, :update, :destroy] do
    member do
      get 'pick_a_card'
      get 'skip'
      get 'results'
    end
    collection do
      get 'start'
      get 'statistics'
    end
  end
  root 'games#welcome'
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :step

  RANGE = (2..10)
  NUMBERS = RANGE.to_a.map { |i| i.to_s }
  ROYALS = ["J", "Q", "K"]
  RANKS = ["A"] + NUMBERS + ROYALS

  def Card.get_card_rank
  	RANKS[rand(12)]
  end

  def Card.get_rank_val_mapping
  	mappings = {}
  	RANGE.each{|r| mappings["#{r}"] = r}
  	ROYALS.each{|r| mappings[r] = 10}
  	mappings["A"] = 11
  	mappings
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :steps, dependent: :destroy
  has_many :cards, through: :steps

  def initialize_steps
  	step = self.steps.create(step_count: 1)
  	step.initialize_cards
  end

  def update_status
  	user_score, dealer_score = get_score
	if (user_score == 21) || (dealer_score > 21) || ((user_score < 21) && (user_score > dealer_score) && (dealer_score >= 17))
		winner = GlobalConstants::USER
		status = GlobalConstants::COMPLETE
	elsif (dealer_score == 21) || (user_score > 21) || ((user_score < 21) && (dealer_score > user_score) && (dealer_score >= 17))
		winner = GlobalConstants::DEALER
		status = GlobalConstants::COMPLETE
	else
		winner = nil
		status = GlobalConstants::PROGRESS
	end
	self.update_attributes(winner: winner, user_score: user_score, dealer_score: dealer_score, status: status)
  end

  def get_score
  	user_score = get_score_of(GlobalConstants::USER)
  	dealer_score = get_score_of(GlobalConstants::DEALER)
	[user_score, dealer_score]
  end

  def completed?
  	self.status == GlobalConstants::COMPLETE
  end

  def get_cards
  	dealer_cards = self.cards.where(card_for: GlobalConstants::DEALER)
  	user_cards = self.cards.where(card_for: GlobalConstants::USER)
  	[dealer_cards, user_cards]
  end

  def next_step
  	self.steps.create(step_count: self.steps.last.step_count + 1)
  end

  def get_score_of(card_for)
  	cards = self.cards.where(card_for: card_for)
  	score = 0
  	cards.each do |card|
		score += Card.get_rank_val_mapping[card.rank]
	end
	score
  end
end

app/models/global_constants.rb
module GlobalConstants
	DEALER = "dealer"
	USER = "user"
	PROGRESS = "progress"
	COMPLETE = "complete"
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :game
  has_many :cards, dependent: :destroy

  def initialize_cards
  	self.cards.create(card_for: GlobalConstants::DEALER, rank: Card.get_card_rank)
  	self.cards.create(card_for: GlobalConstants::USER, rank: Card.get_card_rank)
  	self.cards.create(card_for: GlobalConstants::USER, rank: Card.get_card_rank)
  end

  def pick_a_card
  	self.cards.create(card_for: GlobalConstants::USER, rank: Card.get_card_rank)
  end

  def skip
  	self.cards.create(card_for: GlobalConstants::DEALER, rank: Card.get_card_rank)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def welcome
	end

	def start
		@game = Game.create(status: GlobalConstants::PROGRESS)
		@game.initialize_steps
		@game.update_status
		@dealer_cards, @user_cards = @game.get_cards
		if @game.completed?
			redirect_to :action => 'results', :id => @game.id and return
		end
	end

	def results
		@game = Game.find(params[:id])
	end

	def pick_a_card
		@game = Game.find(params[:id])
		@step = @game.next_step
		@step.pick_a_card
		@game.update_status
		@dealer_cards, @user_cards = @game.get_cards
		if @game.completed?
			redirect_to :action => 'results', :id => @game.id and return
		end
		render 'start'
	end

	def skip
		@game = Game.find(params[:id])
		@step = @game.next_step
		while @game.get_score_of(GlobalConstants::DEALER) <= 16
			@step.skip
		end
		@game.update_status
		@dealer_cards, @user_cards = @game.get_cards
		if @game.completed?
			redirect_to :action => 'results', :id => @game.id and return
		end
		render 'start'
	end

	def statistics
		@games = Game.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
	def get_dealer_class(game)
		game.winner == "dealer" ? "won" : "lost"
	end

	def get_user_class(game)
		game.winner == "user" ? "won" : "lost"
	end
end

app/views/games/_card.html.erb
<li>
	<%= card.rank %>
</li>

app/views/games/results.html.erb
<div id="results-div">
	<div>
		<div class="col-sm-2 col-md-2 col-lg-2"></div>
		<div class="col-sm-8 col-md-8 col-lg-8">
			<p id="results">
				<%= @game.winner.upcase %><br/>
				WINS!
			</p><br/>
			<div class="row">
				<div class="col-sm-6 col-md-6 col-lg-6">
					<%= link_to "DEAL AGAIN", root_path, :class => "btn btn-lg deal-again" %>
				</div>
				<div class="col-sm-6 col-md-6 col-lg-6">
					<%= link_to "STATISTICS", statistics_games_path, :class => "btn btn-lg statistics" %>
				</div>
			</div>
		</div>
		<div class="col-sm-2 col-md-2 col-lg-2"></div>
	</div>
</div>

app/views/games/start.html.erb
<div id="start-div">
	<div>
		<div class="col-sm-2 col-md-2 col-lg-2"></div>
		<div class="col-sm-4 col-md-4 col-lg-4" id="dealer-div">
			<div>
				<h3>DEALER</h3><br/>
				<h5>SCORE: <%= @game.dealer_score %></h5><br/>
				<ul>
					<% @dealer_cards.each do |card| %>
						<%= render "card", card: card %>
					<% end %>
				</ul>
			</div>
		</div>
		<div class="col-sm-4 col-md-4 col-lg-4" id="user-div">
			<div>
				<h3 id="user-header">USER</h3><br/>
				<h5>SCORE: <%= @game.user_score %></h5><br/>
				<ul>
					<% @user_cards.each do |card| %>
						<%= render "card", card: card %>
					<% end %>
				</ul>
			</div><br/>
			<div class="row">
				<div class="col-sm-6 col-md-6 col-lg-6">
					<%= link_to "PICK A CARD", pick_a_card_game_path(@game), :class => "btn btn-md btn-success" %>
				</div>
				<div class="col-sm-6 col-md-6 col-lg-6">
					<%= link_to "SKIP", skip_game_path(@game), :class => "btn btn-md btn-danger" %>
				</div>
			</div>
		</div>
		<div class="col-sm-2 col-md-2 col-lg-2"></div>
	</div>
</div>

app/views/games/statistics.html.erb
<div id="statistics-div">
	<h1>STATISTICS</h1><br/>
	<table class="table" id="statistics-table">
		<thead>
			<tr>
				<td style="border-left: 1px transparent !important"></td>
				<% count = 1%>
				<% for game in @games %>
					<td class="game-sl">GAME <%= count %></td>
					<% count += 1 %>
				<% end %>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td id="dealer-td" style="border-left:1px transparent !important">DEALER</td>
				<% for game in @games %>
					<td class="<%= get_dealer_class(game) %>"><%= game.dealer_score %></td>
				<% end %>
			</tr>
			<tr>
				<td id="user-td" style="border-left: 1px transparent !important">USER</td>
				<% for game in @games %>
					<td class="<%= get_user_class(game) %>"><%= game.user_score %></td>
				<% end %>
			</tr>
		</tbody>
	</table>
	<br/>
	<%= link_to "DEAL AGAIN", root_path, :class => "btn btn-lg btn-success" %>
</div>

app/views/games/welcome.html.erb
<div id="welcome-div">
	<div>
		<div class="col-sm-2 col-md-2 col-lg-2"></div>
		<div class="col-sm-8 col-md-8 col-lg-8">
			<h1>WELCOME</h1><br/>
			<%= link_to "START", start_games_path, :class => "btn btn-lg" %>
		</div>
		<div class="col-sm-2 col-md-2 col-lg-2"></div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Blackjack</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="row">
		<div class="col-sm-2 col-md-2 col-lg-2"></div>
		<div class="col-sm-8 col-md-8 col-lg-8" id="main-div">
			<%= yield %>
		</div>
		<div class="col-sm-2 col-md-2 col-lg-2"></div>
	</div>
</body>
</html>